export const apis = [
  { url: 'https://restcountries.com/', name: 'Rest Countries API' },
  { url: 'https://openweathermap.org/', name: 'OpenWeatherMap API' },
  { url: 'https://pokeapi.co/', name: 'PokéAPI' },
  { url: 'https://api.chucknorris.io/', name: 'Chuck Norris Jokes API' },
  { url: 'https://v2.jokeapi.dev/', name: 'JokeAPI' },
  { url: 'https://thedogapi.com/', name: 'The Dog API' },
  { url: 'https://thecatapi.com/', name: 'The Cat API' },
  { url: 'https://swapi.dev/', name: 'Star Wars API' },
  { url: 'https://api.nasa.gov/', name: 'NASA API' },
  { url: 'https://pixabay.com/api/docs/', name: 'Pixabay API' },
  { url: 'https://jsonplaceholder.typicode.com/', name: 'JSONPlaceholder API' },
  { url: 'https://covid19api.com/', name: 'COVID-19 API' },
  { url: 'https://covid19tracking.narrativa.com/', name: 'COVID-19 Tracking API' },
  { url: 'https://docs.openaq.org/', name: 'OpenAQ API' },
  { url: 'https://rickandmortyapi.com/', name: 'Rick and Morty API' },
  { url: 'http://numbersapi.com/', name: 'Numbers API' },
  { url: 'https://developers.giphy.com/docs/api/', name: 'GIPHY API' },
  { url: 'https://opentdb.com/', name: 'Open Trivia Database API' },
  { url: 'https://www.countryflags.io/', name: 'Country Flags API' },
  { url: 'https://www.themoviedb.org/documentation/api', name: 'The Movie Database API' },
  { url: 'https://exchangeratesapi.io/', name: 'Exchange Rates API' },
  { url: 'https://deckofcardsapi.com/', name: 'Deck of Cards API' },
  { url: 'https://jikan.moe/', name: 'Jikan API' },
  { url: 'https://www.potterapi.com/', name: 'Harry Potter API' },
  { url: 'https://world.openfoodfacts.org/data', name: 'Open Food Facts API' },
  { url: 'https://futuramaapi.herokuapp.com/', name: 'Futurama API' },
  { url: 'http://www.recipepuppy.com/about/api/', name: 'Recipe Puppy API' },
  { url: 'https://api.restyaboard.com/', name: 'Restyaboard API' },
  { url: 'https://epic.gsfc.nasa.gov/about/api', name: 'EPIC API' },
  { url: 'https://breakingbadapi.com/', name: 'Breaking Bad API' },
  { url: 'https://unsplash.com/developers', name: 'Unsplash API' },
  { url: 'https://api.urbandictionary.com/v0/', name: 'Urban Dictionary API' },
  { url: 'https://www.boredapi.com/', name: 'Bored API' },
  { url: 'https://jisho.org/forum/54fefc1f6e73340b1f160000-is-there-any-kind-of-search-api', name: 'Jisho API' },
  { url: 'https://www.football-data.org/', name: 'Football Data API' },
  { url: 'https://www.nps.gov/subjects/developer/api-documentation.htm', name: 'National Park Service API' },
  { url: 'http://avatars.adorable.io/', name: 'Adorable Avatars API' },
  { url: 'https://images.nasa.gov/docs/images.nasa.gov_api_docs.pdf', name: 'NASA Image and Video Library API' },
  { url: 'https://developer.marvel.com/', name: 'Marvel Comics API' },
  { url: 'https://www.thecocktaildb.com/api.php', name: 'The Cocktail DB API' },
  { url: 'https://openlibrary.org/developers/api', name: 'Open Library API' },
  { url: 'https://www.coingecko.com/api/documentation', name: 'CoinGecko API' },
  { url: 'https://github.com/evz/tacofancy-api', name: 'TacoFancy API' },
  { url: 'https://exoplanetarchive.ipac.caltech.edu/docs/program_interfaces.html', name: 'Exoplanet Archive API' },
  { url: 'https://www.brewerydb.com/developers', name: 'BreweryDB API' },
  { url: 'https://icanhazdadjoke.com/api', name: 'icanhazdadjoke API' },
  { url: 'https://www.exchangerate-api.com/', name: 'ExchangeRate-API' },
  { url: 'https://developers.giphy.com/docs/api/endpoint#random', name: 'GIPHY Random API' },
  { url: 'https://punkapi.com/', name: 'Punk API' },
  { url: 'https://aviationapi.com/', name: 'AviationAPI' },
  { url: 'https://api.judge0.com/', name: 'Judge0 API' },
  { url: 'http://www.zippopotam.us/', name: 'Zippopotam.us API' },
  { url: 'https://docs.spacexdata.com/', name: 'SpaceX API' },
];
