export const jobs = [
    { url: 'https://www.linkedin.com', name: 'LinkedIn', type: true },
    { url: 'https://www.fiverr.com/', name: 'Fiverr', type: true },
    { url: 'https://www.upwork.com/', name: 'Upwork', type: true },
    { url: 'https://www.workana.com/', name: 'Workana', type: true },
    { url: 'https://www.turing.com', name: 'Turing', type: true },
    { url: 'http://www.remote.co', name: 'Remote.co', type: true },
    { url: 'https://www.ainetwork.ai/', name: 'AI Network' },
    { url: 'https://www.remoterocketship.com/?page=1&sort=DateAdded', name: 'Remote Rocketship' },
    { url: 'http://www.remoteok.io', name: 'Remoteok' },
    { url: 'https://www.remotive.io', name: 'Remotive' },
    { url: 'https://www.flexjobs.com', name: 'Flexjobs' },
    { url: 'https://www.justremote.co', name: 'Justremote' },
    { url: 'https://www.remotefront.io', name: 'Remotefront' },
    { url: 'https://www.powertofly.com', name: 'Powertofly' },
    { url: 'https://www.skipthedrive.com', name: 'Skipthedrive' },
    { url: 'https://www.authenticjobs.com', name: 'Authenticjobs' },
    { url: 'http://www.ar.computrabajo.com/', name: 'Computrabajo', type: true, arg: true },
    { url: 'https://trabajo.buenosaires.gob.ar/', name: 'TrabajoBA', type: true, arg: true },
]