import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import SideBar from '@/components/SideBar'
import Title from '@/components/Title'
import Provider from '@/components/Provider'
// import Comments from '@/components/Comments'
import Link from 'next/link'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UDR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8881430598289766"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body
        className={`${nunito.className} bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-50 transition-all`}
      >
        <Provider>
          <main className="w-fit mx-auto px-4 my-32 grid grid-rows-[min-content_1fr] grid-cols-1">
            <Title />
            <br />
            <div className="grid grid-cols-[1fr_min-content] grid-rows-1 gap-6">
              <div className="max-w-prose">
                {children}
                <br />
                <p>
                  Si este proyecto te ayudó, considerá{' '}
                  <a
                    href="https://github.com/Patag1"
                    target="_blank"
                    className="text-cyan-500 hover:underline underline-offset-2"
                  >
                    compartirlo
                  </a>
                  , dejar una estrella en el{' '}
                  <a
                    href="https://github.com/Patag1/UDR"
                    target="_blank"
                    className="text-cyan-500 hover:underline underline-offset-2"
                  >
                    repositorio
                  </a>
                  {/*{' '}
                  o{' '}
                  <a
                    href="/"
                    className="text-cyan-500 hover:underline underline-offset-2"
                  >
                    dejar un comentario
                  </a>{' '}
                  con tu feedback*/}
                  . Además sentite libre de utilizar esta página como centro de
                  recursos personales.
                </p>
                {/* <Comments /> */}
                <div className="w-full flex flex-col justify-center items-center">
                  <p className="w-1/2 mt-4 text-center text-xs text-gray-400">
                    Cada feedback que da una persona ayuda a salvar a las
                    ballenas contra la caza indiscriminada, xd
                  </p>
                  <Link
                    href={'/privacy'}
                    className="text-cyan-500 hover:underline text-xs"
                  >
                    Política de Privacidad
                  </Link>
                </div>
              </div>
              <SideBar />
            </div>
          </main>
        </Provider>
      </body>
    </html>
  )
}
